title: GalaxyHosting - Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.galaxyhosting.gg
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Front Website
      description: This is our main website.
      category: Core
      link: https://galaxyhosting.gg/
    - name: Billing
      description: This is the client area where you can manage your servers
        (renewing, tickets, cancellations).
      category: Core
      link: https://galaxyhosting.gg/clientarea.php
    - name: Game Panel
      description: The panel where you manage your server(s).
      category: Core
      link: https://panel.galaxyhosting.gg/.
    - name: EU01
      category: Europe
    - name: EU02
      category: Europe
    - name: CA01
      category: Canada
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Core
      description: The core of GalaxyHosting.
      closed: false
    - name: Europe
      description: Server status in Europe.
      closed: false
    - name: Canada
      description: Server status in Canada
      closed: false
    - name: US West Coast
      description: Server status in the West Coast.
      closed: true
    - name: North America
      description: Server status in North America.
      closed: true
    - name: Australia
      description: Server status in Australia.
      closed: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
